# An example config file for an experiment.
# Keep this, it's used as an example to run the code after a user installs the project.

defaults:
  # Common setup.
  - setup
  # This file.
  - _self_
  # Reward model (from the configs/reward_model/ directory).
  - reward_model: armorm
  # Dataset (from the configs/dataset/ directory).
  - dataset: magpieair


######################################################################

split: ${dataset_args.train_split.name} # train or eval
subpartition_number: 0 # (gpu level) subsection in the partition to process
save_interval: 8192 # Saving every save_interval prompt (should be multiple of batch_size)
batch_size: 16
max_seq_length: 4096

# Used instead of job_subdir, because job_subdir will be populated at runtime with the subpartition number
job_subdir_prefix: null
job_subdir: ${job_subdir_prefix}/${subpartition_number}

dataset_args:
  debug_oom: false # Reorder the dataset with largest batch first to test OOM

seed: 43
