# @package _global_

# https://huggingface.co/datasets/allenai/tulu-3-sft-olmo-2-mixture-0225

dataset_args:
  dataset_name: ${artifacts_dir}/shared/datasets/sft/olmo2-32b-sft
  train_split:
    name: train
  eval_split:
    name: null

training_args:
  eval_strategy: "no"
  eval_steps: null
