# @package _global_

# https://huggingface.co/datasets/allenai/olmo-2-0325-32b-preference-mix


dataset_args:
  dataset_name: ${artifacts_dir}/shared/datasets/alignment-pipeline/datasets-with-chosen-rewards/merged/olmo2-32b-preference-armorm-llama3-8b
  train_split:
    name: train
    start: 0
    end: 367913 # After filtering rows on reward_tokenizer(prompt + chosen/reject) <= 4096
  eval_split:
    name: null

training_args:
  eval_strategy: "no"
  eval_steps: null
